# Python numpy

In [4]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)

[1 2 3 4 5]


### Primeros pasos

In [45]:
# Definir un array
a = np.array([1,2,3,4,5,6])
print(a)
type(a)

[1 2 3 4 5 6]


numpy.ndarray

In [21]:
# Definir un array 2d
b = np.array( [[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
# array de shape: (3,2,2,2)
b1 = np.array([[[[1,2],[1,2]],[[1,2],[1,2]]],[[[1,2],[1,2]],[[1,2],[1,2]]],[[[1,2],[1,2]],[[1,2],[1,2]]]])
print(b1)

[[[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]]


In [79]:
# Definir un array de dimensión 2 (4,2)
b = np.array([[1,2],[3,4],[5,6],[7,8]])
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
# Defir array 3d (2,2,2)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# dimensiones de un array
print('dimensión c: ', c.ndim)
print('dimensión a: ', a.ndim)
print('dimensión b: ', b.ndim)
print('dimensión b1: ', b1.ndim) 

dimensión c:  3
dimensión a:  1
dimensión b:  2
dimensión b1:  4


In [39]:
# Forma shape de un array
print('shape c: ', c.shape)
print('shape a: ', a.shape)
print('shape b: ', b.shape)
print('shape b1: ', b1.shape)

shape c:  (2, 2, 2)
shape a:  (6,)
shape b:  (4, 2)
shape b1:  (3, 2, 2, 2)


In [46]:
# Tipo de elemento
print(a.dtype) # 8 bytes

int64


In [83]:
# Definir el tipo de array en el momento de la creación
a = np.array([1,2,3,4,5,6], dtype=np.int64)

array([1, 2, 3, 4, 5, 6])

In [64]:
# Obtener el tamaño total de un array
print('n. elementos', a.size)
print('tamaño de cada elemento', a.itemsize)
print('tamaño total', a.size * a.itemsize)

n. elementos 6
tamaño de cada elemento 8
tamaño total 48


In [68]:
# Número de elementos que tiene un array
print('elementos a: ', a.size)
print('elementos b: ', b.size)

elementos a:  6
elementos b:  8


In [70]:
# Definir arrays con range
print(a)

[1 2 3 4 5 6]


In [72]:
# Otra forma de inicializar arrays
# Se pueden definir aray mediante un rango
e = np.arange(10) # Rango de 0 a 10
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
e2 = np.arange(10,20) # Rango de 10 a 20
print(e2)

[10 11 12 13 14 15 16 17 18 19]


In [80]:
e3 = np.arange(10,50, 5) # Rango de 10 a 50 de 5 en 5
e3

array([10, 15, 20, 25, 30, 35, 40, 45])

Ejercicios

In [ ]:
'''
Define el array 'a' del 1 al 10
'''

'''
Imprime la dimension del array y el shape
'''

In [ ]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''

In [ ]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''

'''
Imprime el número total de elementos del array y el shape
'''

## Accediendo y Modificando elementos de un array

In [85]:
a = np.array([7,6,3,8,1,6,9])
print(a)

[7 6 3 8 1 6 9]


Obtener un elemento de un array

In [87]:
# Elemento de la primera posición
print(a[0])

7

In [89]:
# [7 6 3 8 1 6 9]
#  0 1 2 3 4 5 6
# Obtener el 8
print(a[3])

8


In [91]:
# Error out of range
# a[16]

In [96]:
# podemos emplear indices negativos
# Selecciona elúltimo elemento
print(a[-1])
# Otros indices negativos
print(a[-3])

9
1


In [105]:
b = np.array([4,5,7,2,7,9,3,2,4,5,7,9,5,4,3,5,8,0,2])
print(b)

[4 5 7 2 7 9 3 2 4 5 7 9 5 4 3 5 8 0 2]


In [115]:
# Selección de rango de elementos
# b[inicio: final]
print(b[0:5])

[4 5 7 2 7]


In [117]:
# Selección de los elementos con índice del 5 al 15
print(b[5:15])

[9 3 2 4 5 7 9 5 4 3]


In [119]:
# b[inicio:final:paso]
print(b[5:15:2])

[9 2 5 9 4]


In [121]:
print(b[15:0:-2])

[5 4 9 5 2 9 2 5]


In [124]:
# Si no se indica delante nada el inicio es implícito
print(b[:10])

[4 5 7 2 7 9 3 2 4 5]


In [125]:
# Desde una posición hasta el final
print(b[5:])

[9 3 2 4 5 7 9 5 4 3 5 8 0 2]


Obtener una fila completa de un array

In [135]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [149]:
# Obtener un elemento en 2d
# se selecciona [fila, columna]
c[1,1]

7

In [140]:
# Obtener segunda fila
print(c[1,:])

[ 6  7  8  9 10]


Obtener una columna completa de un array

In [151]:
print(c[:,2])

# Cambiar forma del array
print(c[:,2].reshape(2,1))

[3 8]
[[3]
 [8]]


Otras formas de acceder a los elementos de un array

In [152]:
# Elemetos en posiciones pares de todas las filas
print(c[:, 0::2 ])
print(c[:, ::2])

[[ 1  3  5]
 [ 6  8 10]]
[[ 1  3  5]
 [ 6  8 10]]


In [169]:
d = np.arange(40).reshape(10,4)
print(d)

# esto es lo mismo
d = np.arange(40)
d_reshape = d.reshape(10,4)
print(d_reshape)

# reshape en el print (no se modifica d)
d = np.arange(40)
print(d.reshape(10,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


Actualizar un elemento de un array

In [172]:
# Definir un array de una dimension y hacer el reshape (10,4)
e = np.arange(40).reshape(10,4)
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [176]:
# Establecer la pos (0,0) a 99
e[0,0] = 99
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [180]:
# Establecer la posición (2,1) a 0
e[2,1] = 0
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [182]:
# Establecer la última fila a 0
e[-1,:] = 0
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [ 0  0  0  0]]


In [184]:
# Establecer la última fila a [1,2,3,4]
e[-1,:] = [1,2,3,4]
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [ 1  2  3  4]]


In [186]:
# Copiar la fila 4 en la última fila
e[-1,:] = e[4,:]
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [16 17 18 19]]


In [261]:
# Copia la primera columna en la úlitma fila
e[:,-1] = e[:,0]
print(e)

[[99  1  2 99]
 [ 1  5  6  1]
 [ 2  0 10  2]
 [99 13 14 99]
 [16  1  2 16]
 [20  3  4 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


In [195]:
# establece a cero una seccion de (2,2)
e[4:6,1:3] = 0
print(e)

[[99  1  2 99]
 [ 4  5  6  4]
 [ 8  0 10  8]
 [12 13 14 12]
 [16  0  0 16]
 [20  0  0 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


In [262]:
# Introduce el [[1,2],[3,4]] en la cuarta fila
e[4:6,1:3] = np.array([1,2,3,4]).reshape(2,2)
print(e)

[[99  1  2 99]
 [ 1  5  6  1]
 [ 2  0 10  2]
 [99 13 14 99]
 [16  1  2 16]
 [20  3  4 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


In [204]:
# Copia la primera fila sobre la primera columna
e[0:4,0] = e[0,:]
print(e)

[[99  1  2 99]
 [ 1  5  6  4]
 [ 2  0 10  8]
 [99 13 14 12]
 [16  1  2 16]
 [20  3  4 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


Ejercicios

In [ ]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''

In [ ]:
'''
Sobre el array s, selecciona el valor 5
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''

In [ ]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''

In [ ]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""

In [ ]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''

In [ ]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''

## Inicializando diferentes tipos de arrays

Matriz de ceros

In [220]:
# podemos inicializar con valor (1dimensión) o shape(n dimensiones)
ceros = np.zeros(10)
print(ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Matriz de unos

In [259]:
unos = np.ones((10,5))
print(unos)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Matriz de valores concretos

In [211]:
valores = np.full((3,3), 99 )
print(valores)

[[99 99 99]
 [99 99 99]
 [99 99 99]]


Matriz de valores concretos (full like)

In [228]:
# Copia el shape de otro array y lo rellena con el valor dado
full_like = np.full_like(valores, 13)
print(full_like)
print(valores)

[[13 13 13]
 [13 13 13]
 [13 13 13]]
[[99 99 99]
 [99 99 99]
 [99 99 99]]


Matriz de números aleatorios

In [231]:
aleatorios = np.random.rand(20)
print(aleatorios)

[0.20029645 0.54616436 0.66673358 0.45113058 0.08482192 0.23543459
 0.40605832 0.9751584  0.67046319 0.10525014 0.28186645 0.91514665
 0.35744401 0.93814664 0.63907633 0.837339   0.39175088 0.60401733
 0.11857797 0.05342424]


In [233]:
# Números aleatorios entre 0 y 1 en una matriz sde (4,3)
f = np.random.rand(4,3)
print(f)

[[0.77701254 0.06248942 0.75925363]
 [0.42360044 0.53030515 0.92454471]
 [0.06027024 0.49223403 0.0220057 ]
 [0.32744674 0.57580944 0.42106464]]


In [237]:
# Numeros aleatorios de 0 a 100 en una matriz de 1d de tamaño 10
g = np.random.randint(100, size=10 )
print(g)

[88 80 80 38 57 54 24 53 44 25]


In [246]:
# Números aleatorios de 50 a 100 en una matriz de 2d de tamaño (4,2)
h = np.random.randint(50,100, size=(4,2))
print(h)

[[85 99]
 [76 97]
 [78 76]
 [96 63]]


In [248]:
# Números aleatorios de 40 a 50 en una matriz de 3d de tamaño (4,3,2)
j = np.random.randint(40,50, size=(4,3,2))
print(j)

[[[45 40]
  [40 40]
  [46 47]]

 [[47 41]
  [42 45]
  [46 48]]

 [[43 49]
  [42 49]
  [41 42]]

 [[46 49]
  [43 49]
  [40 49]]]


Matriz identidad

In [260]:
identidad = np.identity(5)
print(identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejercicios

In [ ]:
'''
Define el array z de dim 1 completo de ceros
'''

In [ ]:
'''
Define un array z de dim 8x8 completo de ceros
'''

In [ ]:
'''
Define el array 'z' completo de ceros de n dim
'''

In [ ]:
'''
Define el array 'd' completo de unos de n dim
'''

In [ ]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

In [ ]:
'''
Define un array 'g' conun range de 0 a 10 de dim 2
'''

In [ ]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''

## Operaciones con arrays

operaciones básicas

In [ ]:
a = np.array([1, 2, 3, 4, 5])

Ejercicios

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y comprueba que los valores son correctos.
'''

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''


In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''

Álgebra lineal

Estadísticas

operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.flip():** Inversa de un array


Cargar datos de un fichero

Máscaras booleanas y operaciones avanzadas