# Python numpy

In [2]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np
import pandas as pd

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)

[1 2 3 4 5]


### Primeros pasos

In [45]:
# Definir un array
a = np.array([1,2,3,4,5,6])
print(a)
type(a)

[1 2 3 4 5 6]


numpy.ndarray

In [21]:
# Definir un array 2d
b = np.array( [[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
# array de shape: (3,2,2,2)
b1 = np.array([[[[1,2],[1,2]],[[1,2],[1,2]]],[[[1,2],[1,2]],[[1,2],[1,2]]],[[[1,2],[1,2]],[[1,2],[1,2]]]])
print(b1)

[[[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]]


In [79]:
# Definir un array de dimensión 2 (4,2)
b = np.array([[1,2],[3,4],[5,6],[7,8]])
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
# Defir array 3d (2,2,2)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# dimensiones de un array
print('dimensión c: ', c.ndim)
print('dimensión a: ', a.ndim)
print('dimensión b: ', b.ndim)
print('dimensión b1: ', b1.ndim) 

dimensión c:  3
dimensión a:  1
dimensión b:  2
dimensión b1:  4


In [39]:
# Forma shape de un array
print('shape c: ', c.shape)
print('shape a: ', a.shape)
print('shape b: ', b.shape)
print('shape b1: ', b1.shape)

shape c:  (2, 2, 2)
shape a:  (6,)
shape b:  (4, 2)
shape b1:  (3, 2, 2, 2)


In [46]:
# Tipo de elemento
print(a.dtype) # 8 bytes

int64


In [83]:
# Definir el tipo de array en el momento de la creación
a = np.array([1,2,3,4,5,6], dtype=np.int64)

array([1, 2, 3, 4, 5, 6])

In [64]:
# Obtener el tamaño total de un array
print('n. elementos', a.size)
print('tamaño de cada elemento', a.itemsize)
print('tamaño total', a.size * a.itemsize)

n. elementos 6
tamaño de cada elemento 8
tamaño total 48


In [68]:
# Número de elementos que tiene un array
print('elementos a: ', a.size)
print('elementos b: ', b.size)

elementos a:  6
elementos b:  8


In [70]:
# Definir arrays con range
print(a)

[1 2 3 4 5 6]


In [72]:
# Otra forma de inicializar arrays
# Se pueden definir aray mediante un rango
e = np.arange(10) # Rango de 0 a 10
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
e2 = np.arange(10,20) # Rango de 10 a 20
print(e2)

[10 11 12 13 14 15 16 17 18 19]


In [80]:
e3 = np.arange(10,50, 5) # Rango de 10 a 50 de 5 en 5
e3

array([10, 15, 20, 25, 30, 35, 40, 45])

Ejercicios

In [ ]:
'''
Define el array 'a' del 1 al 10
'''

'''
Imprime la dimension del array y el shape
'''

In [ ]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''

In [ ]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''

'''
Imprime el número total de elementos del array y el shape
'''

## Accediendo y Modificando elementos de un array

In [85]:
a = np.array([7,6,3,8,1,6,9])
print(a)

[7 6 3 8 1 6 9]


Obtener un elemento de un array

In [87]:
# Elemento de la primera posición
print(a[0])

7

In [89]:
# [7 6 3 8 1 6 9]
#  0 1 2 3 4 5 6
# Obtener el 8
print(a[3])

8


In [91]:
# Error out of range
# a[16]

In [96]:
# podemos emplear indices negativos
# Selecciona elúltimo elemento
print(a[-1])
# Otros indices negativos
print(a[-3])

9
1


In [105]:
b = np.array([4,5,7,2,7,9,3,2,4,5,7,9,5,4,3,5,8,0,2])
print(b)

[4 5 7 2 7 9 3 2 4 5 7 9 5 4 3 5 8 0 2]


In [115]:
# Selección de rango de elementos
# b[inicio: final]
print(b[0:5])

[4 5 7 2 7]


In [117]:
# Selección de los elementos con índice del 5 al 15
print(b[5:15])

[9 3 2 4 5 7 9 5 4 3]


In [119]:
# b[inicio:final:paso]
print(b[5:15:2])

[9 2 5 9 4]


In [121]:
print(b[15:0:-2])

[5 4 9 5 2 9 2 5]


In [124]:
# Si no se indica delante nada el inicio es implícito
print(b[:10])

[4 5 7 2 7 9 3 2 4 5]


In [125]:
# Desde una posición hasta el final
print(b[5:])

[9 3 2 4 5 7 9 5 4 3 5 8 0 2]


Obtener una fila completa de un array

In [135]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [149]:
# Obtener un elemento en 2d
# se selecciona [fila, columna]
c[1,1]

7

In [140]:
# Obtener segunda fila
print(c[1,:])

[ 6  7  8  9 10]


Obtener una columna completa de un array

In [151]:
print(c[:,2])

# Cambiar forma del array
print(c[:,2].reshape(2,1))

[3 8]
[[3]
 [8]]


Otras formas de acceder a los elementos de un array

In [152]:
# Elemetos en posiciones pares de todas las filas
print(c[:, 0::2 ])
print(c[:, ::2])

[[ 1  3  5]
 [ 6  8 10]]
[[ 1  3  5]
 [ 6  8 10]]


In [169]:
d = np.arange(40).reshape(10,4)
print(d)

# esto es lo mismo
d = np.arange(40)
d_reshape = d.reshape(10,4)
print(d_reshape)

# reshape en el print (no se modifica d)
d = np.arange(40)
print(d.reshape(10,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


Actualizar un elemento de un array

In [172]:
# Definir un array de una dimension y hacer el reshape (10,4)
e = np.arange(40).reshape(10,4)
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [176]:
# Establecer la pos (0,0) a 99
e[0,0] = 99
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [180]:
# Establecer la posición (2,1) a 0
e[2,1] = 0
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [182]:
# Establecer la última fila a 0
e[-1,:] = 0
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [ 0  0  0  0]]


In [184]:
# Establecer la última fila a [1,2,3,4]
e[-1,:] = [1,2,3,4]
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [ 1  2  3  4]]


In [186]:
# Copiar la fila 4 en la última fila
e[-1,:] = e[4,:]
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [16 17 18 19]]


In [261]:
# Copia la primera columna en la úlitma fila
e[:,-1] = e[:,0]
print(e)

[[99  1  2 99]
 [ 1  5  6  1]
 [ 2  0 10  2]
 [99 13 14 99]
 [16  1  2 16]
 [20  3  4 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


In [195]:
# establece a cero una seccion de (2,2)
e[4:6,1:3] = 0
print(e)

[[99  1  2 99]
 [ 4  5  6  4]
 [ 8  0 10  8]
 [12 13 14 12]
 [16  0  0 16]
 [20  0  0 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


In [262]:
# Introduce el [[1,2],[3,4]] en la cuarta fila
e[4:6,1:3] = np.array([1,2,3,4]).reshape(2,2)
print(e)

[[99  1  2 99]
 [ 1  5  6  1]
 [ 2  0 10  2]
 [99 13 14 99]
 [16  1  2 16]
 [20  3  4 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


In [204]:
# Copia la primera fila sobre la primera columna
e[0:4,0] = e[0,:]
print(e)

[[99  1  2 99]
 [ 1  5  6  4]
 [ 2  0 10  8]
 [99 13 14 12]
 [16  1  2 16]
 [20  3  4 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


Ejercicios

In [ ]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''

In [ ]:
'''
Sobre el array s, selecciona el valor 5
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''

In [ ]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''

In [ ]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""

In [ ]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''

In [ ]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''

In [12]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''
s4 = np.arange(48).reshape(4,4,3)
s4[:,1:-1,1] = np.arange(8).reshape(4,2)
print(s4)

[[[ 0  1  2]
  [ 3  0  5]
  [ 6  1  8]
  [ 9 10 11]]

 [[12 13 14]
  [15  2 17]
  [18  3 20]
  [21 22 23]]

 [[24 25 26]
  [27  4 29]
  [30  5 32]
  [33 34 35]]

 [[36 37 38]
  [39  6 41]
  [42  7 44]
  [45 46 47]]]


## Inicializando diferentes tipos de arrays

Matriz de ceros

In [220]:
# podemos inicializar con valor (1dimensión) o shape(n dimensiones)
ceros = np.zeros(10)
print(ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Matriz de unos

In [259]:
unos = np.ones((10,5))
print(unos)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Matriz de valores concretos

In [211]:
valores = np.full((3,3), 99 )
print(valores)

[[99 99 99]
 [99 99 99]
 [99 99 99]]


Matriz de valores concretos (full like)

In [228]:
# Copia el shape de otro array y lo rellena con el valor dado
full_like = np.full_like(valores, 13)
print(full_like)
print(valores)

[[13 13 13]
 [13 13 13]
 [13 13 13]]
[[99 99 99]
 [99 99 99]
 [99 99 99]]


Matriz de números aleatorios

In [231]:
aleatorios = np.random.rand(20)
print(aleatorios)

[0.20029645 0.54616436 0.66673358 0.45113058 0.08482192 0.23543459
 0.40605832 0.9751584  0.67046319 0.10525014 0.28186645 0.91514665
 0.35744401 0.93814664 0.63907633 0.837339   0.39175088 0.60401733
 0.11857797 0.05342424]


In [233]:
# Números aleatorios entre 0 y 1 en una matriz sde (4,3)
f = np.random.rand(4,3)
print(f)

[[0.77701254 0.06248942 0.75925363]
 [0.42360044 0.53030515 0.92454471]
 [0.06027024 0.49223403 0.0220057 ]
 [0.32744674 0.57580944 0.42106464]]


In [237]:
# Numeros aleatorios de 0 a 100 en una matriz de 1d de tamaño 10
g = np.random.randint(100, size=10 )
print(g)

[88 80 80 38 57 54 24 53 44 25]


In [246]:
# Números aleatorios de 50 a 100 en una matriz de 2d de tamaño (4,2)
h = np.random.randint(50,100, size=(4,2))
print(h)

[[85 99]
 [76 97]
 [78 76]
 [96 63]]


In [248]:
# Números aleatorios de 40 a 50 en una matriz de 3d de tamaño (4,3,2)
j = np.random.randint(40,50, size=(4,3,2))
print(j)

[[[45 40]
  [40 40]
  [46 47]]

 [[47 41]
  [42 45]
  [46 48]]

 [[43 49]
  [42 49]
  [41 42]]

 [[46 49]
  [43 49]
  [40 49]]]


Matriz identidad

In [260]:
identidad = np.identity(5)
print(identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Ejercicios

In [ ]:
'''
Define el array z de dim 1 completo de ceros
'''

In [ ]:
'''
Define un array z de dim 8x8 completo de ceros
'''

In [ ]:
'''
Define el array 'z' completo de ceros de n dim
'''

In [ ]:
'''
Define el array 'd' completo de unos de n dim
'''

In [ ]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

In [ ]:
'''
Define un array 'g' conun range de 0 a 10 de dim 2
'''

In [ ]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''

## Operaciones con arrays

operaciones básicas

In [16]:
# listas python

# [1,2,3,4,5] + 2 -> da error no se pueden sumar

# ndarrays numpy

a = np.array([1, 2, 3, 4, 5])
print(a + 2)


[3 4 5 6 7]


In [18]:
a = np.array([1, 2, 3, 4, 5])
print(a - 2)

[-1  0  1  2  3]


In [34]:
# Sumar dos listas
a = [1,2,3,4,5]
b = [6,7,8,9,10]
print('Listas python: ', a + b)

# Suma de arrays
a = np.array([1,2,3,4, 5])
b = np.array([6,7,8,9,10])
print('Numpy arrays: ',a + b)


Listas python:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Numpy arrays:  [ 7  9 11 13 15]


In [121]:
# multiplicación escalar
a = np.array([1,2,3,4, 5])
print(a * 2)


[ 2  4  6  8 10]


In [123]:
# Elevar los elementos al cuadrado
a = np.array([1,2,3,4, 5])
print(a)
print( a ** 2)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [24]:
# Si ambos array no son tiene el mismo shape no se pueden operar
a = np.array([1,2,3,4])
b = np.array([6,7,8,9,10])
#a + b

In [126]:
# 2dimensiones
c = np.arange(9).reshape(3,3)
d = np.arange(9,18).reshape(3,3)
print(c,'\n')
print(d, '\n')
print(c+d)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [38]:
# Multiplicación de matrices
# Ejemplo:
c = np.arange(9).reshape(3,3)
d = np.arange(9,18).reshape(3,3)
print(c)
print(d)

# multiplica: 
# [0,0] = c[0,0] * d[0,0] + c[1,0] * d[0,1] + c[2,0] * d[0,2]
#               0                  12            30

print(np.matmul(c,d))
# Otras formas:
print( c.dot(d))
print( c @ d ) 


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [45]:
# Obtener la matrix traspuesta
e = np.arange(24).reshape(6,4)
print(e)
print(np.transpose(e))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


Ejercicios

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y comprueba que los valores son correctos.
'''

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''

Álgebra lineal

Estadísticas

operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.flip():** Inversa de un array


In [47]:
a = np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [49]:
# sumatorio
sumatorio = np.sum(a)
sumatorio

276

In [54]:
# sumatorio de la primera fila
primera_fila = a[0,:]
sumatorio_primera_fila = np.sum(primera_fila)
sumatorio_primera_fila
# Otra forma
print(np.sum(a[0,:]))

6


In [56]:
# Promedio de los valores
promedio = np.mean(a)
promedio

11.5

In [58]:
# promerio de la primera columna
print(np.mean(a[:,0]))

10.0


In [62]:
# mínimo valor de una matriz
minimo = np.min(a)
minimo

0

In [65]:
# máximo de una matriz
maximo = np.max(a)
maximo

23

In [74]:
# máximo de una seccion de array
max_seccion = np.max(a[1:,:])
max_seccion

23

In [77]:
# flip 1d
a = np.arange(10)
print(a)
print(np.flip(a))

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [84]:
a = np.arange(24).reshape(6,4)
print(a,'\n')
print(np.flip(a),'\n')
print('Traspuesta:\n', np.transpose(a))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[23 22 21 20]
 [19 18 17 16]
 [15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]] 

Traspuesta:
 [[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


### Reorganizando matrices

In [91]:
# Reshape. Reorganiza el array con la forma indicada
a = np.random.rand(100)
print(a)
print(a.shape, '\n')

print(a.reshape(10,10))
print(a.reshape(10,10).shape)


[0.25366325 0.62815683 0.15480888 0.03337842 0.392229   0.72311053
 0.67442362 0.9095328  0.93173654 0.3733687  0.60256391 0.43539933
 0.66404101 0.41980805 0.71668982 0.39710375 0.05495269 0.05048192
 0.02365273 0.14255564 0.36734444 0.82494767 0.10045144 0.09293812
 0.91555491 0.43929201 0.06958075 0.92501197 0.87874451 0.85924535
 0.23223349 0.80240351 0.71568038 0.00115385 0.62400744 0.18973862
 0.3644716  0.30891498 0.67241392 0.51107678 0.56847448 0.28030457
 0.00596967 0.72864625 0.50952741 0.73993779 0.31245871 0.89947618
 0.20183402 0.02114831 0.01530476 0.62101425 0.83759163 0.98105788
 0.58363256 0.2041373  0.05676846 0.72562215 0.01330515 0.01770166
 0.37278338 0.18307542 0.18595578 0.45357273 0.21103288 0.90073925
 0.08686697 0.9195035  0.4575071  0.66191503 0.77604028 0.21499604
 0.78044164 0.08942131 0.16001637 0.33607951 0.10109995 0.77620781
 0.43824298 0.65929621 0.29577874 0.74082144 0.53041285 0.60651943
 0.07696077 0.1854062  0.97027351 0.47036301 0.48767218 0.6358

In [99]:
# Apilar arrays
a = np.arange(5)
b = np.arange(6,11)
c = np.arange(11,6,-1)

np.vstack([c,b,a])

array([[11, 10,  9,  8,  7],
       [ 6,  7,  8,  9, 10],
       [ 0,  1,  2,  3,  4]])

In [107]:
# apilar arrays horinzontal
a = np.arange(24).reshape(6,4)
b = np.arange(24,0,-1).reshape(6,4)
print(a, '\n')
print(b, '\n')
np.hstack([a,b])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[24 23 22 21]
 [20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]] 



array([[ 0,  1,  2,  3, 24, 23, 22, 21],
       [ 4,  5,  6,  7, 20, 19, 18, 17],
       [ 8,  9, 10, 11, 16, 15, 14, 13],
       [12, 13, 14, 15, 12, 11, 10,  9],
       [16, 17, 18, 19,  8,  7,  6,  5],
       [20, 21, 22, 23,  4,  3,  2,  1]])

In [111]:
# apilar arrays 3d
a = np.arange(24).reshape(6,4)
b = np.arange(24,0,-1).reshape(6,4)
print(a, '\n')
print(b, '\n')
print(np.dstack([a,b]))
print(np.dstack([a,b]).shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[24 23 22 21]
 [20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]] 

[[[ 0 24]
  [ 1 23]
  [ 2 22]
  [ 3 21]]

 [[ 4 20]
  [ 5 19]
  [ 6 18]
  [ 7 17]]

 [[ 8 16]
  [ 9 15]
  [10 14]
  [11 13]]

 [[12 12]
  [13 11]
  [14 10]
  [15  9]]

 [[16  8]
  [17  7]
  [18  6]
  [19  5]]

 [[20  4]
  [21  3]
  [22  2]
  [23  1]]]
(6, 4, 2)


In [117]:
# Concatenar en la 3d
print(np.array([a,b]))
print(np.array([a,b]).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 23 22 21]
  [20 19 18 17]
  [16 15 14 13]
  [12 11 10  9]
  [ 8  7  6  5]
  [ 4  3  2  1]]]
(2, 6, 4)


Cargar datos de un fichero

In [210]:
import numpy as np
'''
1,2,13,4,15,6,17,8,19,10
11,2,13,4,5,16,7,18,9,20
21,12,23,6,25,8,27,1,29,1
31,2,33,4,35,6,37,8,39,10
41,12,43,6,45,8,47,1,49,1
'''
fichero = np.genfromtxt('numpy_values.txt', delimiter=',')
fichero = fichero.astype(int)
print(fichero)
print(type(fichero))
print(fichero.shape)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [41 12 43  6 45  8 47  1 49  1]]
<class 'numpy.ndarray'>
(5, 10)


Máscaras booleanas y operaciones avanzadas

In [160]:
# Generar una másca booleana
# La máscara filtra los valores > 40
mayores_40 = fichero > 40
print(mayores_40)


[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [ True False  True False  True False  True False  True False]]


In [161]:
# Aplicar máscara booleana
fichero[mayores_40]

# otra forma
# fichero[fichero > 40]

array([41, 43, 45, 47, 49])

In [163]:
# poner a 0 los valores > 40
fichero[mayores_40] = 0
print(fichero)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [ 0 12  0  6  0  8  0  1  0  1]]


In [178]:
# Concatenar condiciones
mayores_30_menores_40 = (fichero > 30) & (fichero < 40)
print(mayores_30_menores_40)


[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [ True False  True False  True False  True False  True False]
 [False False False False False False False False False False]]


In [174]:
# Aplica máscara contatenar condiciones
fichero[mayores_30_menores_40]

array([31, 33, 35, 37, 39])

In [185]:
# Negar condición
no_mayores_30_menores_40 = np.logical_not((fichero > 30) & (fichero < 40))
print(no_mayores_30_menores_40)

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [False  True False  True False  True False  True False  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [186]:
print(fichero[no_mayores_30_menores_40])

[ 1  2 13  4 15  6 17  8 19 10 11  2 13  4  5 16  7 18  9 20 21 12 23  6
 25  8 27  1 29  1  2  4  6  8 10 41 12 43  6 45  8 47  1 49  1]


In [188]:
# Any
# hay algún valor mayor que 50?
np.any(fichero > 50)

False

In [196]:
# Any se puede especificar si la comprobación es por filas o columna con axis=
# Obtener las columna que contienen un valor > 40
print(fichero,'\n')
column_mayores_40 = np.any(fichero > 40, axis=0)
print(column_mayores_40)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [41 12 43  6 45  8 47  1 49  1]] 

[ True False  True False  True False  True False  True False]


In [194]:
# aplicar máscar de columnas
fichero[:,column_mayores_40]

array([[ 1, 13, 15, 17, 19],
       [11, 13,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [197]:
# Filtro por filas
print(fichero,'\n')
filas_mayores_40 = np.any(fichero > 40, axis=1)
print(filas_mayores_40)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [41 12 43  6 45  8 47  1 49  1]] 

[False False False False  True]


In [202]:
# Aplicar la máscara
fichero[filas_mayores_40,:]

array([[41, 12, 43,  6, 45,  8, 47,  1, 49,  1]])

In [204]:
# Filtro por filas
print(fichero,'\n')
filas_menores_47 = np.any(fichero < 47, axis=1)
print(filas_menores_47)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [41 12 43  6 45  8 47  1 49  1]] 

[ True  True  True  True  True]


In [206]:
# Aplicar ambas máscaras
fichero[filas_mayores_40,column_mayores_40]

array([41, 43, 45, 47, 49])

In [207]:
# Aplicar ambas máscaras
fichero[filas_menores_47,column_mayores_40]

array([ 1, 13, 25, 37, 49])

In [208]:
fichero[fichero > 40]

array([41, 43, 45, 47, 49])

In [217]:
np.argwhere((fichero > 40))

array([[4, 0],
       [4, 2],
       [4, 4],
       [4, 6],
       [4, 8]])