# Python numpy

In [ ]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)

In [ ]:
# Teoría
# aplicaciones numpy


### Primeros pasos

Ejercicios

In [ ]:
'''
Define el array 'a' del 1 al 10
'''

'''
Imprime la dimension del array y el shape
'''

In [ ]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''

In [ ]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''

'''
Imprime el número total de elementos del array y el shape
'''

## Accediendo y Modificando elementos de un array

Obtener un elemento de un array

Obtener una fila completa de un array

Obtener una columna completa de un array

Otras formas de acceder a los elementos de un array

Actualizar un elemento de un array

Ejercicios

In [ ]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''

In [ ]:
'''
Sobre el array s, selecciona el valor 5
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''

In [ ]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''

In [ ]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""

In [ ]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''

In [ ]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''

## Inicializando diferentes tipos de arrays

Matriz de ceros

Matriz de unos

Matriz de valores concretos

Matriz de valores concretos (full like)

Matriz de números aleatorios

Matriz identidad

Ejercicios

In [ ]:
'''
Define el array z de dim 1 completo de ceros
'''

In [ ]:
'''
Define un array z de dim 8x8 completo de ceros
'''

In [ ]:
'''
Define el array 'z' completo de ceros de n dim
'''

In [ ]:
'''
Define el array 'd' completo de unos de n dim
'''

In [ ]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

In [ ]:
'''
Define un array 'g' conun range de 0 a 10 de dim 2
'''

In [ ]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''

## Operaciones con arrays

operaciones básicas

In [ ]:
a = np.array([1, 2, 3, 4, 5])

Ejercicios

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y comprueba que los valores son correctos.
'''

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''


In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''

Álgebra lineal

Estadísticas

operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.flip():** Inversa de un array


Cargar datos de un fichero

Máscaras booleanas y operaciones avanzadas